export const HOME_GET_DATA_ATTEMPT = 'HOME_GET_DATA_ATTEMPT';
export const HOME_GET_DATA_SUCCESS = 'HOME_GET_DATA_SUCCESS';
export const HOME_GET_DATA_FAILED = 'HOME_GET_DATA_FAILED';
export const HOME_CLEAR_DATA_ARRAY = 'HOME_CLEAR_DATA_ARRAY';
export const HOME_CLEAR_DATA = 'HOME_CLEAR_DATA';
